<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AGDATA.Rewards.Core\AGDATA.Rewards.Core.csproj" />
    <ProjectReference Include="..\AGDATA.Rewards.Infrastructure\AGDATA.Rewards.Infrastructure.csproj" />
    <ProjectReference Include="..\AGDATA.Rewards.Application\AGDATA.Rewards.Application.csproj" />
  </ItemGroup>

</Project>
